Update cURL version to 7.86.0.

diff --git a/extensions/curl/curl-src/maketgz b/extensions/curl/curl-src/maketgz
--- a/extensions/curl/curl-src/maketgz
+++ b/extensions/curl/curl-src/maketgz
@@ -1,6 +1,30 @@
-#! /bin/sh
-# Script to build release-archives with
+#!/bin/sh
+# Script to build release-archives with. Note that this requires a checkout
+# from git and you should first run ./buildconf and build curl once.
 #
+#***************************************************************************
+#                                  _   _ ____  _
+#  Project                     ___| | | |  _ \| |
+#                             / __| | | | |_) | |
+#                            | (__| |_| |  _ <| |___
+#                             \___|\___/|_| \_\_____|
+#
+# Copyright (C) 1998 - 2022, Daniel Stenberg, <daniel@haxx.se>, et al.
+#
+# This software is licensed as described in the file COPYING, which
+# you should have received as part of this distribution. The terms
+# are also available at https://curl.se/docs/copyright.html.
+#
+# You may opt to use, copy, modify, merge, publish, distribute and/or sell
+# copies of the Software, and permit persons to whom the Software is
+# furnished to do so, under the terms of the COPYING file.
+#
+# This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
+# KIND, either express or implied.
+#
+# SPDX-License-Identifier: curl
+#
+###########################################################################
 
 version=$1
 
@@ -9,51 +33,78 @@ if [ -z "$version" ]; then
   exit
 fi
 
+if [ "xonly" = "x$2" ]; then
+  echo "Setup version number only!"
+  only=1
+fi
+
 libversion="$version"
 
 # we make curl the same version as libcurl
 curlversion=$libversion
 
-major=`echo $libversion |cut -d. -f1 | sed -e "s/[^0-9]//g"`
-minor=`echo $libversion |cut -d. -f2 | sed -e "s/[^0-9]//g"`
-patch=`echo $libversion |cut -d. -f3 | cut -d- -f1 | sed -e "s/[^0-9]//g"`
+major=`echo $libversion | cut -d. -f1 | sed -e "s/[^0-9]//g"`
+minor=`echo $libversion | cut -d. -f2 | sed -e "s/[^0-9]//g"`
+patch=`echo $libversion | cut -d. -f3 | cut -d- -f1 | sed -e "s/[^0-9]//g"`
+
+if test -z "$patch"; then
+  echo "invalid version number? needs to be z.y.z"
+  exit
+fi
+
+#
+# As a precaution, remove all *.dist files that may be lying around, to reduce
+# the risk of old leftovers getting shipped. The root 'Makefile.dist' is the
+# exception.
+echo "removing all old *.dist files"
+find . -name "*.dist" -a ! -name Makefile.dist -exec rm {} \;
 
 numeric=`perl -e 'printf("%02x%02x%02x\n", '"$major, $minor, $patch);"`
 
 HEADER=include/curl/curlver.h
-CHEADER=src/version.h
+CHEADER=src/tool_version.h
+PLIST=lib/libcurl.plist
 
-# requires a date command that knows -u for UTC time zone
-datestamp=`date -u`
+if test -z "$only"; then
+  ext=".dist"
+  # when not setting up version numbers locally
+  for a in $HEADER $CHEADER $PLIST; do
+    cp $a "$a$ext"
+  done
+  HEADER="$HEADER$ext"
+  CHEADER="$CHEADER$ext"
+  PLIST="$PLIST$ext"
+fi
+
+# requires a date command that knows + for format
+datestamp=`date +"%F"`
 
 # Replace version number in header file:
-sed -e 's/^#define LIBCURL_VERSION .*/#define LIBCURL_VERSION "'$libversion'"/g' \
+sed -i.bak \
+    -e 's/^#define LIBCURL_VERSION .*/#define LIBCURL_VERSION "'$libversion'"/g' \
     -e 's/^#define LIBCURL_VERSION_NUM .*/#define LIBCURL_VERSION_NUM 0x'$numeric'/g' \
     -e 's/^#define LIBCURL_VERSION_MAJOR .*/#define LIBCURL_VERSION_MAJOR '$major'/g' \
     -e 's/^#define LIBCURL_VERSION_MINOR .*/#define LIBCURL_VERSION_MINOR '$minor'/g' \
     -e 's/^#define LIBCURL_VERSION_PATCH .*/#define LIBCURL_VERSION_PATCH '$patch'/g' \
     -e "s/^#define LIBCURL_TIMESTAMP .*/#define LIBCURL_TIMESTAMP \"$datestamp\"/g" \
- $HEADER >$HEADER.dist
+    $HEADER
+rm -f "$HEADER.bak"
 
 # Replace version number in header file:
-sed 's/#define CURL_VERSION .*/#define CURL_VERSION "'$curlversion'"/g' $CHEADER >$CHEADER.dist
+sed -i.bak 's/#define CURL_VERSION .*/#define CURL_VERSION "'$curlversion'"/g' $CHEADER
+rm -f "$CHEADER.bak"
 
-echo "generate VC8 makefiles"
-# Generate VC8 versions from the VC6 Makefile versions 
-perl -pe 's%/GX /DWIN32 /YX%/EHsc /DWIN32%;' -e 's%/GZ%/RTC1%;' -e 's%wsock32.lib%wsock32.lib bufferoverflowu.lib%g;' -e 's%(VC)6%${1}8%gi;' lib/Makefile.vc6 > lib/Makefile.vc8.dist
-perl -pe "s%/GX /DWIN32 /YX%/EHsc /DWIN32%;" -e 's%/GZ%/RTC1%;' -e 's%wsock32.lib%wsock32.lib bufferoverflowu.lib%g;' -e 's%(VC)6%${1}8%gi;' -e 's/^#MANIFESTTOOL/MANIFESTTOOL/' src/Makefile.vc6 > src/Makefile.vc8.dist
-
-# Replace version number in plist file:
-PLIST=lib/libcurl.plist
-sed "s/7\.12\.3/$libversion/g" $PLIST > $PLIST.dist
+if test -n "$only"; then
+  # done!
+  exit;
+fi
 
 echo "curl version $curlversion"
 echo "libcurl version $libversion"
 echo "libcurl numerical $numeric"
 echo "datestamp $datestamp"
 
-findprog()
-{
+findprog() {
   file="$1"
   for part in `echo $PATH| tr ':' ' '`; do
     path="$part/$file"
@@ -66,9 +117,6 @@ findprog()
   # no such executable
   return 0
 }
-
-echo "maketgz: cp lib/config.h.in src/config.h.in"
-cp lib/config.h.in src/config.h.in
 
 ############################################################################
 #
@@ -93,14 +141,23 @@ fi
 
 ############################################################################
 #
-# Make sure we have updated HTML versions of all man pages:
+# Modify the man pages to display the version number and date.
 #
-echo "make html"
-make -s html
 
-# And the PDF versions
-echo "make pdf"
-make -s pdf
+echo "update man pages"
+./scripts/updatemanpages.pl $version >/dev/null
+
+# make the generated file newer than the man page
+touch src/tool_hugehelp.c
+
+############################################################################
+#
+# Update the IDE files
+echo "make vc-ide"
+make -s vc-ide
+
+echo "produce CHANGES"
+git log --pretty=fuller --no-color --date=short --decorate=full -1000 | ./scripts/log2changes.pl > CHANGES.dist
 
 ############################################################################
 #
@@ -109,7 +166,13 @@ make -s pdf
 
 echo "make dist"
 targz="curl-$version.tar.gz"
-make -s dist VERSION=$version
+make -sj dist VERSION=$version
+res=$?
+
+if test "$res" != 0; then
+    echo "make dist failed"
+    exit 2
+fi
 
 ############################################################################
 #
@@ -118,14 +181,22 @@ make -s dist VERSION=$version
 
 bzip2="curl-$version.tar.bz2"
 echo "Generating $bzip2"
-gzip -dc $targz | bzip2 - > $bzip2
+gzip -dc $targz | bzip2 --best > $bzip2
+
+############################################################################
+#
+# Now make an xz archive from the tar.gz original
+#
+
+xz="curl-$version.tar.xz"
+echo "Generating $xz"
+gzip -dc $targz | xz -6e - > $xz
 
 ############################################################################
 #
 # Now make a zip archive from the tar.gz original
 #
-makezip ()
-{
+makezip() {
   rm -rf $tempdir
   mkdir $tempdir
   cd $tempdir
@@ -144,9 +215,7 @@ makezip
 echo "------------------"
 echo "maketgz report:"
 echo ""
-ls -l $targz $bzip2 $zip
-
-md5sum $targz $bzip2 $zip
+ls -l $targz $bzip2 $zip $xz
 
 echo "Run this:"
-echo "gpg -b -a $targz && gpg -b -a $bzip2 && gpg -b -a $zip"
+echo "gpg -b -a $targz && gpg -b -a $bzip2 && gpg -b -a $zip && gpg -b -a $xz"
